spring:
  application:
    name: seat-lock
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/seatlock}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 1000           # Batch Insert 크기
        order_inserts: true          # INSERT 쿼리 정렬
        order_updates: true          # UPDATE 쿼리 정렬
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: DEBUG                          # SQL 쿼리 로그
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 파라미터 바인딩 로그
  file:
    name: logs/application.log    # 로그 파일 경로 및 이름
    path: logs                     # 로그 디렉토리
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{requestId}] [%X{transactionId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{requestId}] [%X{transactionId}] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB         # 파일 하나당 최대 크기
      max-history: 30             # 최대 30일치 보관
      total-size-cap: 1GB